apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_DB: dG9kb19kYXRhYmFzZQ==
  POSTGRES_USER: aGFyc2g=
  POSTGRES_PASSWORD: YWJjZDEyMzQ=
  POSTGRES_HOST: cG9zdGdyZXMtc2VydmljZQ==