apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: todo-config
        image: harshvishu/todo-web-image:latest
        name: todo-web
        ports:
        - containerPort: 8000
