apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
      - name: todo-web
        image: harshvishu/todo-web-image:latest
        env:
        - name: TODO_API_URL
          value: "http://todo-api:8000"
        ports:
        - containerPort: 8000
