apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)
        envFrom:
        - secretRef:
            name: db-secrets
        image: harshvishu/todo-api-image:latest
        name: todo-api
        ports:
        - containerPort: 8000
